services:
  app:
    build: .
    # volumes:
      # - ./chacha_server:/app
      # - ./chacha_server/.chacha_server:/root/.chacha_server
    ports:
      - "80:8080"
    # stdin_open: true
    # tty: true
    # restart: always
